#!/usr/bin/env bash
set -euo pipefail

# ══════════════════════════════════════════════════════════════
# Phalanx DHCP Setup — Automatic DNS Assignment
#
# Installs and configures dnsmasq as the network's DHCP server.
# Every device that connects to the network will automatically
# receive the Pi's IP as its DNS server — zero manual config.
#
# IMPORTANT: After running this, disable your router's built-in
# DHCP server. Having two DHCP servers causes conflicts.
#
# Failsafe: Every DHCP lease includes a fallback DNS (1.1.1.1)
# so if the Pi goes down, devices can still resolve domains.
# ══════════════════════════════════════════════════════════════

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

echo ""
echo "========================================"
echo "  Phalanx DHCP Auto-Configuration"
echo "========================================"
echo ""

if [[ $EUID -ne 0 ]]; then
    echo "Error: Run as root (sudo bash $0)"
    exit 1
fi

# ── Detect network configuration ──
PI_IP=$(hostname -I | awk '{print $1}')
GATEWAY=$(ip route | grep default | awk '{print $3}')
INTERFACE=$(ip route | grep default | awk '{print $5}')
SUBNET_BASE=$(echo "$PI_IP" | cut -d. -f1-3)

echo "Detected configuration:"
echo "  Interface:  $INTERFACE"
echo "  Pi IP:      $PI_IP"
echo "  Gateway:    $GATEWAY"
echo "  Subnet:     ${SUBNET_BASE}.0/24"
echo ""

# ── DHCP range: .100 to .250 (avoids low static IPs) ──
DHCP_START="${SUBNET_BASE}.100"
DHCP_END="${SUBNET_BASE}.250"
DHCP_LEASE="24h"

echo "DHCP will assign IPs from ${DHCP_START} to ${DHCP_END}"
echo "All devices will use ${PI_IP} as their DNS server"
echo "Fallback DNS: 1.1.1.1 (if Pi goes offline)"
echo ""

read -p "Continue? (y/n): " CONFIRM
[[ "$CONFIRM" != "y" ]] && exit 0

# ── Install dnsmasq ──
echo "[1/4] Installing dnsmasq..."
apt-get update -qq
apt-get install -y -qq dnsmasq

# Stop dnsmasq while we configure it
systemctl stop dnsmasq 2>/dev/null || true

# ── Back up existing config ──
if [[ -f /etc/dnsmasq.conf ]]; then
    cp /etc/dnsmasq.conf /etc/dnsmasq.conf.bak.phalanx
    echo "       Backed up existing dnsmasq.conf"
fi

# ── Write dnsmasq configuration ──
echo "[2/4] Configuring dnsmasq..."

cat > /etc/dnsmasq.conf << EOF
# ══════════════════════════════════════════
# Phalanx DHCP + DNS Configuration
# Generated by setup_dhcp.sh
# ══════════════════════════════════════════

# ── Interface ──
# Only serve DHCP on the local network interface
interface=${INTERFACE}
bind-interfaces

# ── DHCP Server ──
# Assign IPs in this range with 24-hour leases
dhcp-range=${DHCP_START},${DHCP_END},${DHCP_LEASE}

# Tell clients to use THIS Pi as their DNS server
dhcp-option=option:dns-server,${PI_IP},1.1.1.1

# Tell clients the default gateway (your router)
dhcp-option=option:router,${GATEWAY}

# Subnet mask
dhcp-option=option:netmask,255.255.255.0

# Domain name for local network
domain=phalanx.local

# ── DNS Forwarding ──
# Forward DNS queries to Phalanx (localhost port 53)
# Phalanx handles blocking + upstream resolution
server=127.0.0.1#53

# Don't use /etc/resolv.conf for upstream
no-resolv

# Don't forward short/local names upstream
domain-needed
bogus-priv

# ── Logging ──
log-dhcp
log-facility=/var/log/phalanx/dnsmasq.log

# ── Performance ──
cache-size=0
# (Phalanx has its own DNS cache — don't double-cache)

# ── DHCP Lease File ──
dhcp-leasefile=/var/lib/misc/dnsmasq.leases

# ── Authoritative mode ──
# Respond to all DHCP requests (we're the only DHCP server)
dhcp-authoritative

# ── Rapid commit (faster lease assignment) ──
dhcp-rapid-commit
EOF

# ── Ensure log directory exists ──
mkdir -p /var/log/phalanx

# ── Configure dnsmasq to not conflict with Phalanx DNS ──
# dnsmasq normally listens on port 53 for DNS, but Phalanx already does.
# We tell dnsmasq to only handle DHCP, not DNS.
echo "[3/4] Configuring port separation..."

cat >> /etc/dnsmasq.conf << EOF

# ── Port separation ──
# dnsmasq handles DHCP only. Phalanx handles DNS on port 53.
# dnsmasq listens on a high port for its own DNS cache (unused).
port=0
EOF

# ── Start and enable ──
echo "[4/4] Starting dnsmasq..."
systemctl enable dnsmasq
systemctl start dnsmasq

# Verify
if systemctl is-active --quiet dnsmasq; then
    echo ""
    echo "========================================"
    echo "  ✅ DHCP Server Active"
    echo ""
    echo "  Pi IP:         ${PI_IP}"
    echo "  DHCP Range:    ${DHCP_START} — ${DHCP_END}"
    echo "  DNS Server:    ${PI_IP} (Phalanx)"
    echo "  Fallback DNS:  1.1.1.1 (Cloudflare)"
    echo ""
    echo "  NEXT STEP:"
    echo "  1. Log into your router's admin panel"
    echo "  2. Disable the router's DHCP server"
    echo "  3. Reconnect devices (or wait for lease renewal)"
    echo ""
    echo "  Devices will automatically use Phalanx"
    echo "  for DNS — no manual configuration needed."
    echo "========================================"
else
    echo ""
    echo "❌ dnsmasq failed to start."
    echo "   Check: journalctl -u dnsmasq --no-pager -n 20"
    # Restore backup
    if [[ -f /etc/dnsmasq.conf.bak.phalanx ]]; then
        cp /etc/dnsmasq.conf.bak.phalanx /etc/dnsmasq.conf
        echo "   Restored original dnsmasq.conf"
    fi
    exit 1
fi
